#!/bin/bash
# Quick Start Guide for Development Folder

echo "🚀 FRESHWAYS - MERGED DEVELOPMENT SETUP"
echo "========================================"
echo ""
echo "✅ Your code + Friend's code are now merged in: development/"
echo ""
echo "📋 QUICK START STEPS:"
echo ""
echo "Step 1️⃣  - Setup Frontend:"
echo "   cd development/fresh"
echo "   npm install"
echo ""
echo "Step 2️⃣  - Setup Backend:"
echo "   cd ../freshwayz-api"
echo "   npm install"
echo ""
echo "Step 3️⃣  - Configure Database (.env file in freshwayz-api/):"
echo "   DATABASE_HOST=localhost"
echo "   DATABASE_PORT=3306"
echo "   DATABASE_USER=root"
echo "   DATABASE_PASSWORD=your_password"
echo "   DATABASE_NAME=freshways"
echo "   JWT_SECRET=your_secret_key"
echo "   PORT=8080"
echo ""
echo "Step 4️⃣  - Run Both Servers (In separate terminals):"
echo ""
echo "   Terminal 1 (Frontend):"
echo "   cd development/fresh"
echo "   npm run dev"
echo "   → Runs on http://localhost:5173"
echo ""
echo "   Terminal 2 (Backend):"
echo "   cd development/freshwayz-api"
echo "   npm run start:dev"
echo "   → Runs on http://localhost:8080"
echo ""
echo "✨ DONE! Your application is ready:"
echo "   • Frontend: http://localhost:5173"
echo "   • Backend: http://localhost:8080"
echo "   • API Docs: http://localhost:8080/api/docs"
echo "   • Username: admin"
echo "   • Password: supersecret"
echo ""
echo "📚 Read MERGE_SUMMARY.md for detailed information"
echo ""
